---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: infra
spec:
  acme:
    email: amsy810@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: testbed.54.168.200.143.nip.io
  namespace: infra
spec:
  secretName: testbed-cert
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
  - testbed.54.168.200.143.nip.io
  - argocd.54.168.200.143.nip.io
  - tekton.54.168.200.143.nip.io
  - harbor.54.168.200.143.nip.io
  - notary.54.168.200.143.nip.io
  - dashboard.54.168.200.143.nip.io
  - rook.54.168.200.143.nip.io
  - prometheus.54.168.200.143.nip.io
  - grafana.54.168.200.143.nip.io
  - alertmanager.54.168.200.143.nip.io
  - weave-scope.54.168.200.143.nip.io
  - yugabyte.54.168.200.143.nip.io
  - minio.54.168.200.143.nip.io
  commonName: testbed.54.168.200.143.nip.io
